---
title: "handson6"
author: "Ningzhen"
date: '2022-05-21'
output: html_document
---


```{r echo=TRUE}
packages = c( 'sf','tmap','tidyverse','lubridate',
              'clock','sftime','rmarkdown')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

```{r echo=TRUE,eval=FALSE}
school=read_sf('C:/Users/65873/Downloads/Visual Analytics/VAST-Challenge-2022/Datasets/Attributes/Schools.csv',options='GEOM_POSSIBLE_NAMES=location')

pub=read_sf('C:/Users/65873/Downloads/Visual Analytics/VAST-Challenge-2022/Datasets/Attributes/Pubs.csv',options='GEOM_POSSIBLE_NAMES=location')

apartment=read_sf('C:/Users/65873/Downloads/Visual Analytics/VAST-Challenge-2022/Datasets/Attributes/Apartments.csv',options='GEOM_POSSIBLE_NAMES=location')

restaurant=read_sf('C:/Users/65873/Downloads/Visual Analytics/VAST-Challenge-2022/Datasets/Attributes/Restaurants.csv',options='GEOM_POSSIBLE_NAMES=location')

employer=read_sf('C:/Users/65873/Downloads/Visual Analytics/VAST-Challenge-2022/Datasets/Attributes/Employers.csv',options='GEOM_POSSIBLE_NAMES=location')

building=read_sf('C:/Users/65873/Downloads/Visual Analytics/VAST-Challenge-2022/Datasets/Attributes/Buildings.csv',options='GEOM_POSSIBLE_NAMES=location')


```


```{r echo=TRUE,eval=FALSE}
tmap_mode('view')
tm_shape(building)+
  tm_polygons(col="grey60",
  size=1,
  border.col='black',
  border.lwd=1)
tmap_mode('plot')
```


```{r,eval=FALSE}
tmap_mode("view")
tm_shape(building)+
tm_polygons(col = "grey60",
           size = 1,
           border.col = "black",
           border.lwd = 1) +
tm_shape(employer) +
  tm_dots(col = "red")
```


```{r,eval=FALSE}
logs=read_sf('C:/Users/65873/Downloads/Visual Analytics/VAST-Challenge-2022/Datasets/Activity Logs/ParticipantStatusLogs1.csv',options='GEOM_POSSIBLE_NAMES=currentLocation')
#sf cannot recognize time
#sf_time?

```

```{r,eval=FALSE}
logs_selected<-logs%>% 
  mutate(Timestamp=date_time_parse(timestamp,
                                   zone="",
                                format="%Y-%m-%dT&H:%M:%S"))
logs_selected<-logs_selected %>%
  mutate(day=get_day(Timestamp))%>%
  filter(currentMode=='Transport')

```

```{r,eval=FALSE}
write_rds(logs_selected,"logs_selected.rds")

```

```{r,eval=FALSE}
log_selected<-read_rds('logs_selected.rds')
hex <- st_make_grid(building, #define the bbox 
                    cellsize=100, #dimention:100x100
                    square=FALSE) %>%
  st_sf() %>%
  rowid_to_column('hex_id')
points_in_hex <- st_join(log_selected, 
                        hex, 
                        join=st_within) %>%
  st_set_geometry(NULL) %>%
  count(name='pointCount', hex_id)
head(points_in_hex)
hex_combined <- hex %>%
  left_join(points_in_hex, 
            by = 'hex_id') %>%
  replace(is.na(.), 0)
```


```{r,eval=FALSE}
tm_shape(hex_combined %>%
           filter(pointCount > 0))+
  tm_fill("pointCount",
          n = 8,
          style = "quantile") +
  tm_borders(alpha = 0.1)
```